/**
 * tal_adc.h — TAL ADC: pad-centric ADC ergonomics
 *
 * Wraps hal_adc using coregen-generated pad→channel mappings
 * (core_pad_adc_channel(), PAD_n_ADC_CH) and SYSCLK_HZ so that
 * application code can work entirely in pad numbers — the same
 * numbers used in project.json and on the tile silkscreen.
 *
 * Requires: core_pads.h, core_config.h (both generated by coregen).
 *
 * Typical usage:
 *
 *   #include "tal_adc.h"
 *
 *   hal_adc_t adc;
 *   tal_adc_init(&adc, HAL_ADC_RES_12BIT);
 *   tal_adc_add_pad(&adc, 5, HAL_ADC_SAMP_MED);
 *
 *   uint32_t mv = tal_adc_read_pad_mv(&adc, 5);
 *
 * Compare to the HAL equivalent:
 *
 *   hal_adc_init(&adc, ADC4, SYSCLK_HZ, HAL_ADC_RES_12BIT);  // need instance + clock
 *   hal_adc_add_channel(&adc, PAD_5_ADC_CH, HAL_ADC_SAMP_MED);  // need channel number
 *   uint32_t mv = hal_adc_read_mv(&adc, PAD_5_ADC_CH);
 *
 * Oversampling, DMA, and burst reads are not wrapped — call hal_adc directly:
 *   hal_adc_set_oversample(&adc, HAL_ADC_OVERSAMPLE_64X);
 *   hal_adc_read_all(&adc, buf);
 *   hal_adc_start_dma(&adc, buf, len, callback);
 */

#ifndef TAL_ADC_H
#define TAL_ADC_H

#include "hal_adc.h"
#include "core_pads.h"    /* core_pad_adc_channel(), PAD_n_ADC_CH */
#include "core_config.h"  /* SYSCLK_HZ */

/* ============================================================
 * Core ADC instance
 *
 * Each Core tile has a single primary ADC peripheral.
 * Resolved from the MCU family define injected by the Makefile.
 * ============================================================ */

#if defined(STM32WBA55xx)
  /** Core.W — WBA55 has a single ADC (ADC4, on AHB4) */
  #define CORE_ADC_INSTANCE   ADC4
#else
  /** Core.L / Core.U / Core.H — all use ADC1 */
  #define CORE_ADC_INSTANCE   ADC1
#endif

/* ============================================================
 * Init
 * ============================================================ */

/**
 * Initialise the ADC.
 *
 * Equivalent to hal_adc_init(adc, CORE_ADC_INSTANCE, SYSCLK_HZ, res).
 * No need to look up which ADC peripheral your Core uses or what
 * SYSCLK_HZ is — both are resolved from coregen output.
 *
 * @param adc  Uninitialised handle
 * @param res  Conversion resolution (HAL_ADC_RES_12BIT for most uses)
 */
static inline hal_status_t tal_adc_init(hal_adc_t *adc, hal_adc_res_t res)
{
    return hal_adc_init(adc, CORE_ADC_INSTANCE, SYSCLK_HZ, res);
}

/* ============================================================
 * Channel registration
 * ============================================================ */

/**
 * Add a pad as an ADC input.
 *
 * Looks up the ADC channel number for pad via the coregen-generated
 * core_pad_adc_channel() helper, then calls hal_adc_add_channel.
 *
 * Returns HAL_ERROR if pad has no ADC function (not assigned as analog
 * in project.json, or the pad does not support ADC on this Core).
 *
 * @param adc   Initialised handle
 * @param pad   Tile pad number (e.g. 5 for pad 5)
 * @param samp  Sampling time — see hal_adc_samp_t
 */
static inline hal_status_t tal_adc_add_pad(hal_adc_t *adc, uint8_t pad,
                                            hal_adc_samp_t samp)
{
    int ch = core_pad_adc_channel(pad);
    if (ch < 0) return HAL_ERROR;   /* pad not ADC-capable or not assigned */
    return hal_adc_add_channel(adc, (uint8_t)ch, samp);
}

/* ============================================================
 * Blocking reads
 * ============================================================ */

/**
 * Single-shot blocking read — returns raw ADC count.
 *
 * @param adc  Initialised handle
 * @param pad  Pad number (must have been added via tal_adc_add_pad)
 * @return     Raw ADC count (0–4095 at 12-bit); 0 if pad is invalid
 */
static inline uint16_t tal_adc_read_pad(hal_adc_t *adc, uint8_t pad)
{
    int ch = core_pad_adc_channel(pad);
    if (ch < 0) return 0;
    return hal_adc_read(adc, (uint8_t)ch);
}

/**
 * Single-shot blocking read — returns VREFINT-calibrated millivolts.
 *
 * Uses the VREFINT factory calibration to account for the actual VDDA
 * supply voltage, so the result is correct even when VDD ≠ 3.3 V.
 *
 * @param adc  Initialised handle
 * @param pad  Pad number (must have been added via tal_adc_add_pad)
 * @return     Voltage in millivolts; 0 if pad is invalid
 */
static inline uint32_t tal_adc_read_pad_mv(hal_adc_t *adc, uint8_t pad)
{
    int ch = core_pad_adc_channel(pad);
    if (ch < 0) return 0;
    return hal_adc_read_mv(adc, (uint8_t)ch);
}

/* ============================================================
 * Internal channels
 *
 * No pad lookup needed — these read the ADC's internal inputs.
 * Provided here for API completeness so code that uses TAL
 * can include only tal_adc.h.
 * ============================================================ */

/**
 * Read die temperature in tenths of °C.
 * Example: 253 = 25.3 °C.
 * Auto-adds the internal temperature channel on first call.
 */
static inline int32_t tal_adc_read_temp_decidegc(hal_adc_t *adc)
{
    return hal_adc_read_temp_decidegc(adc);
}

/**
 * Read actual VDD supply voltage in millivolts via VREFINT.
 * Useful for battery-level estimation and supply-compensated calculations.
 */
static inline uint32_t tal_adc_read_vdda_mv(hal_adc_t *adc)
{
    return hal_adc_read_vdda_mv(adc);
}

#endif /* TAL_ADC_H */
