/**
 * tal_timer.h — TAL Timer: pad-centric PWM ergonomics
 *
 * Wraps hal_timer using coregen-generated pad→timer/channel mappings
 * (core_pad_timer_info(), PAD_n_TIM, PAD_n_TIM_CH) and SYSCLK_HZ so
 * that application code can work entirely in pad numbers — the same
 * numbers used in project.json and on the tile silkscreen.
 *
 * Requires: core_pads.h, core_config.h (both generated by coregen).
 *
 * Typical usage:
 *
 *   #include "tal_timer.h"
 *
 *   hal_timer_t pwm;
 *   tal_pwm_init(&pwm, 7, 1000);           // pad 7 → TIM2.CH3, 1 kHz
 *   tal_pwm_set(&pwm, 7, 500);             // 50% duty
 *   tal_pwm_start(&pwm);
 *
 * Compare to the HAL equivalent:
 *
 *   hal_timer_pwm_init(&pwm, TIM2, SYSCLK_HZ, 1000);
 *   hal_timer_pwm_set_duty(&pwm, 3, 500);
 *   hal_timer_pwm_start(&pwm);
 */

#ifndef TAL_TIMER_H
#define TAL_TIMER_H

#include "core_timer.h"
#include "core_pads.h"    /* core_pad_timer_info(), PAD_n_TIM, PAD_n_TIM_CH */
#include "core_config.h"  /* SYSCLK_HZ */

/* ============================================================
 * PWM output — pad-centric
 * ============================================================ */

/**
 * Initialise a timer for PWM output on the given pad.
 *
 * Resolves the timer instance from the pad's coregen-assigned function.
 * Returns HAL_ERROR if the pad has no timer assignment.
 *
 * @param h        Uninitialised handle
 * @param pad      Pad number (must have TIMx.y assigned in project.json)
 * @param freq_hz  PWM frequency in Hz
 */
static inline hal_status_t tal_pwm_init(core_timer_t *h, uint8_t pad,
                                         uint32_t freq_hz)
{
    TIM_TypeDef *instance;
    uint8_t channel;
    if (core_pad_timer_info(pad, &instance, &channel) != 0) {
        return HAL_ERROR;
    }
    return hal_timer_pwm_init(h, instance, SYSCLK_HZ, freq_hz);
}

/**
 * Set PWM duty cycle on a pad.
 *   duty_permil: 0–1000 (0 = off, 500 = 50%, 1000 = 100%)
 */
static inline void tal_pwm_set(core_timer_t *h, uint8_t pad,
                                uint16_t duty_permil)
{
    TIM_TypeDef *instance;
    uint8_t channel;
    if (core_pad_timer_info(pad, &instance, &channel) != 0) return;
    hal_timer_pwm_set_duty(h, channel, duty_permil);
}

/** Start the PWM timer. */
static inline void tal_pwm_start(core_timer_t *h)
{
    hal_timer_pwm_start(h);
}

/** Stop the PWM timer. */
static inline void tal_pwm_stop(core_timer_t *h)
{
    hal_timer_pwm_stop(h);
}

/** Change PWM frequency (recalculates PSC/ARR, resets all channel duties). */
static inline void tal_pwm_set_freq(core_timer_t *h, uint32_t freq_hz)
{
    hal_timer_pwm_set_freq(h, freq_hz);
}

#endif /* TAL_TIMER_H */
