/**
 * tile_handles.h — Tile driver includes and instance handles for val-spi-u2
 *
 * Initially generated by coregen. The section between coregen markers
 * is kept in sync with project.json automatically — add your own
 * tile-related defines outside the markers.
 *
 * Named tile_handles.h (not tiles.h) so it doesn't shadow tiles.h
 * in the compiler include path.
 */

#ifndef TILE_HANDLES_H
#define TILE_HANDLES_H

/* ---- coregen:begin ---- */
#include "tiles.h"
#include "tiles_pal.h"
#include "core_tiles.h"
#include "tile_sense_i_6p6.h"

/* Tile PAL handles (one per bus used by tiles) */
tiles_pal_t core_pal_spi1;

/* Tile instance handles */
tile_t tile_sense_i_6p6_spi1_0;
/* ---- coregen:end ---- */

#endif /* TILE_HANDLES_H */
