/**
 * core_pads.h — Pad-to-GPIO mapping for Core.H.1
 *
 * AUTO-GENERATED by coregen from Core-H-1-a.json
 * JSON version 0.32, rev a
 *
 * DO NOT EDIT — regenerate with:
 *   python3 tools/coregen/coregen.py tiles/Core-H-1-a.json
 */

#ifndef CORE_PADS_H
#define CORE_PADS_H

#include <stdint.h>

/* ---- Core identity ---- */

#define TILE_FAMILY        "Core"
#define TILE_NAME          "H.1"
#define TILE_FULL_NAME     "Core.H.1"
#define TILE_REV           "a"
#define TILE_HEADLINE      "250MHz Cortex-M33"
#define TILE_PAD_COUNT     14

/* ---- MCU identity ---- */

#define TILE_MCU_PART      "STM32H523HE"
#define TILE_MCU_DEFINE    STM32H523xx
#define TILE_MCU_FAMILY    "stm32h5xx"
#define TILE_MCU_CORE      "cortex-m33"

/* ---- Pad-to-GPIO mapping ---- */
/*
 * Each pad with a GPIO function gets:
 *   PAD_<n>_PORT  — GPIO port base (e.g., GPIOA)
 *   PAD_<n>_PIN   — Pin number within the port
 *   PAD_<n>_GPIO  — Combined P<port><pin> label for comments
 */

/* Pad 1: power (no GPIO) */
/* Pad 2: PA8 */
#define PAD_2_PORT       GPIOA
#define PAD_2_PIN        8
/* Pad 3: PB4 */
#define PAD_3_PORT       GPIOB
#define PAD_3_PIN        4
/* Pad 4: PB8 */
#define PAD_4_PORT       GPIOB
#define PAD_4_PIN        8
/* Pad 5: PB7 */
#define PAD_5_PORT       GPIOB
#define PAD_5_PIN        7
/* Pad 6: PA12 */
#define PAD_6_PORT       GPIOA
#define PAD_6_PIN        12
/* Pad 7: PA11 */
#define PAD_7_PORT       GPIOA
#define PAD_7_PIN        11
/* Pad 8: PA7 */
#define PAD_8_PORT       GPIOA
#define PAD_8_PIN        7
/* Pad 9: PA5 */
#define PAD_9_PORT       GPIOA
#define PAD_9_PIN        5
/* Pad 10: power (no GPIO) */
/* Pad 11: system/no GPIO */
/* Pad 12: system/no GPIO */
/* Pad 13: PA14 */
#define PAD_13_PORT       GPIOA
#define PAD_13_PIN        14
/* Pad 14: PA13 */
#define PAD_14_PORT       GPIOA
#define PAD_14_PIN        13

/* ---- System pads ---- */

#define PAD_SWCLK          13
#define PAD_SWDIO          14
#define PAD_BOOT0          11
#define PAD_NRST           12
#define PAD_VCC            10
#define PAD_GND            1

/* ---- Pin bitmasks (for BSRR, ODR, IDR) ---- */

#define PAD_2_MASK       (1UL << 8)
#define PAD_3_MASK       (1UL << 4)
#define PAD_4_MASK       (1UL << 8)
#define PAD_5_MASK       (1UL << 7)
#define PAD_6_MASK       (1UL << 12)
#define PAD_7_MASK       (1UL << 11)
#define PAD_8_MASK       (1UL << 7)
#define PAD_9_MASK       (1UL << 5)
#define PAD_13_MASK       (1UL << 14)
#define PAD_14_MASK       (1UL << 13)

/* ---- ADC channel mapping ---- */
/* Maps pad numbers to ADC channel numbers for pads with analog functions. */
/* Use with hal_adc_read() or the generated PAD_n_ADC_CH defines. */

#define PAD_8_ADC_CH     7
#define PAD_9_ADC_CH     19

/**
 * Pad-to-ADC-channel lookup (auto-generated).
 * Returns the ADC channel for a pad, or -1 if no ADC on that pad.
 */
static inline int core_pad_adc_channel(uint8_t pad)
{
    switch (pad) {
    case 8: return 7;
    case 9: return 19;
    default: return -1;
    }
}


#endif /* CORE_PADS_H */
