/**
 * core_interfaces.h — Interface pin/AF defines for Core.H.1
 *
 * AUTO-GENERATED by coregen from Core-H-1-a.json
 * JSON version 0.32, rev a
 *
 * DO NOT EDIT — regenerate with:
 *   python3 tools/coregen/coregen.py tiles/Core-H-1-a.json
 */

#ifndef CORE_INTERFACES_H
#define CORE_INTERFACES_H

/*
 * For each interface instance, defines are generated for the
 * required (and common optional) signals:
 *
 *   <IFACE>_<SIGNAL>_PAD    — tile pad number
 *   <IFACE>_<SIGNAL>_PORT   — GPIO port (e.g., GPIOB)
 *   <IFACE>_<SIGNAL>_PIN    — GPIO pin number
 *   <IFACE>_<SIGNAL>_AF     — alternate function number
 *
 * Only signals with a known GPIO mapping and AF are included.
 */

/* ---- I2C1 (I2C) ---- */

#define I2C1_CLK_PAD     4
#define I2C1_CLK_PORT    GPIOB
#define I2C1_CLK_PIN     8
#define I2C1_CLK_AF      4
#define I2C1_DAT_PAD     5
#define I2C1_DAT_PORT    GPIOB
#define I2C1_DAT_PIN     7
#define I2C1_DAT_AF      4

/* ---- I2C3 (I2C) ---- */

#define I2C3_CLK_PAD     2
#define I2C3_CLK_PORT    GPIOA
#define I2C3_CLK_PIN     8
#define I2C3_CLK_AF      4
#define I2C3_DAT_PAD     3
#define I2C3_DAT_PORT    GPIOB
#define I2C3_DAT_PIN     4
#define I2C3_DAT_AF      9

/* ---- SPI1 (SPI) ---- */
/* Max clock: 45MHz */

#define SPI1_RDY_PAD     2
#define SPI1_RDY_PORT    GPIOA
#define SPI1_RDY_PIN     8
#define SPI1_RDY_AF      5
#define SPI1_MISO_PAD     3
#define SPI1_MISO_PORT    GPIOB
#define SPI1_MISO_PIN     4
#define SPI1_MISO_AF      5
#define SPI1_MOSI_PAD     8
#define SPI1_MOSI_PORT    GPIOA
#define SPI1_MOSI_PIN     7
#define SPI1_MOSI_AF      5
#define SPI1_CLK_PAD     9
#define SPI1_CLK_PORT    GPIOA
#define SPI1_CLK_PIN     5
#define SPI1_CLK_AF      5

/* ---- UART4 (UART) ---- */

#define UART4_RX_PAD     4
#define UART4_RX_PORT    GPIOB
#define UART4_RX_PIN     8
#define UART4_RX_AF      8
#define UART4_TX_PAD     6
#define UART4_TX_PORT    GPIOA
#define UART4_TX_PIN     12
#define UART4_TX_AF      6
#define UART4_RX_ALT_PAD     7
#define UART4_RX_ALT_PORT    GPIOA
#define UART4_RX_ALT_PIN     11
#define UART4_RX_ALT_AF      6

/* ---- FDCAN1 (FD CAN) ---- */

#define FDCAN1_RX_PAD     4
#define FDCAN1_RX_PORT    GPIOB
#define FDCAN1_RX_PIN     8
#define FDCAN1_RX_AF      9
#define FDCAN1_TX_PAD     5
#define FDCAN1_TX_PORT    GPIOB
#define FDCAN1_TX_PIN     7
#define FDCAN1_TX_AF      9
#define FDCAN1_TX_ALT_PAD     6
#define FDCAN1_TX_ALT_PORT    GPIOA
#define FDCAN1_TX_ALT_PIN     12
#define FDCAN1_TX_ALT_AF      9
#define FDCAN1_RX_ALT_PAD     7
#define FDCAN1_RX_ALT_PORT    GPIOA
#define FDCAN1_RX_ALT_PIN     11
#define FDCAN1_RX_ALT_AF      9

/* ---- USB (USB) ---- */

#define USB_DP_PAD     6
#define USB_DP_PORT    GPIOA
#define USB_DP_PIN     12
#define USB_DP_AF      10
#define USB_DM_PAD     7
#define USB_DM_PORT    GPIOA
#define USB_DM_PIN     11
#define USB_DM_AF      10
#define USB_SOF_PAD     2
#define USB_SOF_PORT    GPIOA
#define USB_SOF_PIN     8
#define USB_SOF_AF      10

/* ---- I3C2 (I3C) ---- */

#define I3C2_CLK_PAD     2
#define I3C2_CLK_PORT    GPIOA
#define I3C2_CLK_PIN     8
#define I3C2_CLK_AF      9
#define I3C2_DAT_PAD     3
#define I3C2_DAT_PORT    GPIOB
#define I3C2_DAT_PIN     4
#define I3C2_DAT_AF      10

/* ---- I3C1 (I3C) ---- */

#define I3C1_CLK_PAD     4
#define I3C1_CLK_PORT    GPIOB
#define I3C1_CLK_PIN     8
#define I3C1_CLK_AF      3
#define I3C1_DAT_PAD     5
#define I3C1_DAT_PORT    GPIOB
#define I3C1_DAT_PIN     7
#define I3C1_DAT_AF      3

#endif /* CORE_INTERFACES_H */
