/**
 * core_board.h — Board-level defines for Core.ST.H5.1
 *
 * AUTO-GENERATED by coregen from Core-H-1-a.json
 * JSON version 0.32, rev a
 *
 * DO NOT EDIT — regenerate with:
 *   python3 tools/coregen/coregen.py tiles/Core-H-1-a.json
 */

#ifndef CORE_BOARD_H
#define CORE_BOARD_H

/* ---- Onboard LED ---- */

#define LED_PORT           GPIOA
#define LED_PIN            15
#define LED_MASK           (1UL << 15)
#define LED_ACTIVE_HIGH    1
#define LED_ON()           (LED_PORT->BSRR = LED_MASK)
#define LED_OFF()          (LED_PORT->BSRR = (LED_MASK << 16))
#define LED_TOGGLE()       (LED_PORT->ODR ^= LED_MASK)

/* ---- Power ---- */

#define VCC_MIN            1.71f
#define VCC_MAX            3.60f
#define VCC_USB_MIN        3.0f

#endif /* CORE_BOARD_H */
