#include "core.h"
#include "tile_handles.h"
#include "core_ble.h"
#include "ble_services.h"

/* BLE write callbacks (stubs from ble_services.h — fill in your logic) */

void on_aqua_led_write(const uint8_t *data, uint16_t len, void *ctx)
{
    (void)len; (void)ctx;
    if (data[0]) LED_ON();
    else         LED_OFF();
}

int main(void)
{
    /* Initialize clock and pads (generated by coregen) */
    core_init();
    core_led_init();

    /* ---- BLE ---- */
    core_ble_set_services(app_ble_services);
    core_ble_init(CORE_BLE_PAIRING_NONE);
    core_ble_advertise("Core.W");

    uint8_t counter = 0;
    uint32_t last_notify = 0;

    while (1) {
        core_ble_process();

        /* Increment and notify counter every second */
        if (core_ble_connected()) {
            uint32_t now = core_millis();
            if (now - last_notify >= 1000) {
                last_notify = now;
                counter++;
                core_ble_set_value(ble_counter, &counter, 1);
            }
        }
    }
}
