#include "core.h"
#include "core_ble.h"

int main(void)
{
    /* Initialize clock and pads (generated by coregen) */
    core_init();

    /* ---- BLE ---- */
    /* To add GATT services, define a builder and register it before init:
     *   core_ble_set_services(app_ble_services);
     * See tests/ble-test for a worked example. (The SDK build compiles only
     * PROJECT_DIR/*.c, so keep those sources at the project root.) */
    core_ble_init();
    core_ble_advertise("Core.ST.W5");

    while (1) {
        core_ble_process();
        /* Your application code */
    }
}
