#include "core.h"
#include "tile_handles.h"
#include "core_ble.h"

int main(void)
{
    /* Initialize clock and pads (generated by coregen) */
    core_init();

    /* ---- BLE ---- */
    /* To add GATT services, export from the BLE Contract Editor into ble_services/ */
    /* core_ble_set_services(app_ble_services); */
    core_ble_init(CORE_BLE_PAIRING_NONE);
    core_ble_advertise("Core.ST.W5");

    while (1) {
        core_ble_process();
        /* Your application code */
    }
}
