/**
 * core_config.h — Project-specific configuration for Core.U.2
 *
 * AUTO-GENERATED by coregen from Core-U-2-a.json + project.json
 * Project: val-rom-dfu
 *
 * DO NOT EDIT — regenerate by rebuilding the project.
 */

#ifndef CORE_CONFIG_H
#define CORE_CONFIG_H

/* ---- Clock configuration ---- */

#define CLOCK_SOURCE_MSI  1
#define SYSCLK_MHZ        16
#define SYSCLK_HZ         (16UL * 1000000UL)

#define CLOCK_USE_PLL      0

#define AHB_DIV            1
#define APB1_DIV           1
#define APB2_DIV           1

#define HCLK_HZ           (SYSCLK_HZ / AHB_DIV)
#define PCLK1_HZ          (HCLK_HZ / APB1_DIV)
#define PCLK2_HZ          (HCLK_HZ / APB2_DIV)

#define I2C_KERNEL_CLK_MHZ  SYSCLK_MHZ



/* ---- Bootloader ---- */
/*   "custom" — Core DFU bootloader (1209:0002). App at 0x08002000.
 *   "rom"    — ST ROM bootloader (0483:DF11). App at 0x08000000.
 * Configured in project.json: "bootloader": "rom" */
#define BOOTLOADER_MODE  "rom"

#endif /* CORE_CONFIG_H */
