/**
 * core_init.h — Generated initialization API for Core.U.2
 *
 * AUTO-GENERATED by coregen from Core-U-2-a.json + config.json
 * Project: val-rom-dfu
 *
 * DO NOT EDIT — regenerate by rebuilding the project.
 */

#ifndef CORE_INIT_H
#define CORE_INIT_H

/**
 * Initialize the core: clock tree, flash latency, and configured pads.
 * Call this at the top of main() before using any peripherals.
 */
void core_init(void);

/**
 * Initialize the clock tree only.
 * Sets up oscillator, PLL (if needed), flash wait states, bus prescalers,
 * and switches SYSCLK to the configured source.
 */
void core_clock_init(void);

/**
 * Initialize the configured pads.
 * Enables GPIO port clocks and sets modes/AF for all pads
 * assigned in config.json.
 */
void core_pads_init(void);

/**
 * Drain pending pad-edge events and dispatch DSL handlers. Called from
 * the Tessera shim's main loop every iteration. Always safe to call —
 * no-op when no pads have EXTI configured in config.json.
 */
void tessera_dispatch_core_pad(void);

/**
 * Fire the Tessera tick handler once per configured `timer.tick_ms`.
 * No-op when no tick period is set. Always safe to call.
 */
void tessera_dispatch_core_timer(void);

/**
 * Drain the USB CDC RX ring and fire the Tessera byte-receive handler
 * (capped at 64 bytes per call). No-op when USB isn't enabled.
 */
void tessera_dispatch_core_usb(void);

#endif /* CORE_INIT_H */
