/**
 * core_interfaces.h — Interface pin/AF defines for Core.ST.L4.2
 *
 * AUTO-GENERATED by coregen from Core-U-2-a.json
 * JSON version 0.49, rev a
 *
 * DO NOT EDIT — regenerate with:
 *   python3 tools/coregen/coregen.py tiles/Core-U-2-a.json
 */

#ifndef CORE_INTERFACES_H
#define CORE_INTERFACES_H

/*
 * For each interface instance, defines are generated for the
 * required (and common optional) signals:
 *
 *   <IFACE>_<SIGNAL>_PAD    — tile pad number
 *   <IFACE>_<SIGNAL>_PORT   — GPIO port (e.g., GPIOB)
 *   <IFACE>_<SIGNAL>_PIN    — GPIO pin number
 *   <IFACE>_<SIGNAL>_AF     — alternate function number
 *
 * Only signals with a known GPIO mapping and AF are included.
 */

/* ---- I2C1 (I2C) ---- */
/* Max clock: 1MHz */

#define I2C1_SMBA_PAD     3
#define I2C1_SMBA_PORT    GPIOA
#define I2C1_SMBA_PIN     1
#define I2C1_SMBA_AF      4
#define I2C1_CLK_PAD     4
#define I2C1_CLK_PORT    GPIOB
#define I2C1_CLK_PIN     6
#define I2C1_CLK_AF      4
#define I2C1_DAT_PAD     5
#define I2C1_DAT_PORT    GPIOB
#define I2C1_DAT_PIN     7
#define I2C1_DAT_AF      4
#define I2C1_SMBA_ALT_PAD     13
#define I2C1_SMBA_ALT_PORT    GPIOA
#define I2C1_SMBA_ALT_PIN     14
#define I2C1_SMBA_ALT_AF      4

/* ---- I2C3 (I2C) ---- */
/* Max clock: 1MHz */

#define I2C3_CLK_PAD     2
#define I2C3_CLK_PORT    GPIOA
#define I2C3_CLK_PIN     7
#define I2C3_CLK_AF      4
#define I2C3_DAT_PAD     18
#define I2C3_DAT_PORT    GPIOB
#define I2C3_DAT_PIN     4
#define I2C3_DAT_AF      4

/* ---- SPI1 (SPI) ---- */
/* Max clock: 40Mhz (master), 20MHz (slave) */

#define SPI1_CLK_PAD     3
#define SPI1_CLK_PORT    GPIOA
#define SPI1_CLK_PIN     1
#define SPI1_CLK_AF      5
#define SPI1_MOSI_PAD     2
#define SPI1_MOSI_PORT    GPIOA
#define SPI1_MOSI_PIN     7
#define SPI1_MOSI_AF      5
#define SPI1_MISO_PAD     9
#define SPI1_MISO_PORT    GPIOA
#define SPI1_MISO_PIN     6
#define SPI1_MISO_AF      5
#define SPI1_CLK_ALT_PAD     10
#define SPI1_CLK_ALT_PORT    GPIOA
#define SPI1_CLK_ALT_PIN     5
#define SPI1_CLK_ALT_AF      5
#define SPI1_CS_PAD     11
#define SPI1_CS_PORT    GPIOB
#define SPI1_CS_PIN     0
#define SPI1_CS_AF      5
#define SPI1_CLK_ALT2_PAD     12
#define SPI1_CLK_ALT2_PORT    GPIOB
#define SPI1_CLK_ALT2_PIN     3
#define SPI1_CLK_ALT2_AF      5
#define SPI1_MOSI_ALT_PAD     16
#define SPI1_MOSI_ALT_PORT    GPIOA
#define SPI1_MOSI_ALT_PIN     12
#define SPI1_MOSI_ALT_AF      5
#define SPI1_MISO_ALT_PAD     17
#define SPI1_MISO_ALT_PORT    GPIOA
#define SPI1_MISO_ALT_PIN     11
#define SPI1_MISO_ALT_AF      5
#define SPI1_MISO_ALT2_PAD     18
#define SPI1_MISO_ALT2_PORT    GPIOB
#define SPI1_MISO_ALT2_PIN     4
#define SPI1_MISO_ALT2_AF      5
#define SPI1_CS_ALT_PAD     19
#define SPI1_CS_ALT_PORT    GPIOA
#define SPI1_CS_ALT_PIN     4
#define SPI1_CS_ALT_AF      5

/* ---- USB (USB) ---- */

#define USB_DP_PAD     16
#define USB_DP_PORT    GPIOA
#define USB_DP_PIN     12
#define USB_DP_AF      10
#define USB_DM_PAD     17
#define USB_DM_PORT    GPIOA
#define USB_DM_PIN     11
#define USB_DM_AF      10

/* ---- USART1 (USART) ---- */

#define USART1_TX_PAD     4
#define USART1_TX_PORT    GPIOB
#define USART1_TX_PIN     6
#define USART1_TX_AF      7
#define USART1_RX_PAD     5
#define USART1_RX_PORT    GPIOB
#define USART1_RX_PIN     7
#define USART1_RX_AF      7
#define USART1_RTS_DE_PAD     16
#define USART1_RTS_DE_PORT    GPIOA
#define USART1_RTS_DE_PIN     12
#define USART1_RTS_DE_AF      7
#define USART1_CTS_PAD     17
#define USART1_CTS_PORT    GPIOA
#define USART1_CTS_PIN     11
#define USART1_CTS_AF      7
#define USART1_CTS_ALT_PAD     18
#define USART1_CTS_ALT_PORT    GPIOB
#define USART1_CTS_ALT_PIN     4
#define USART1_CTS_ALT_AF      7
#define USART1_RTS_DE_ALT_PAD     12
#define USART1_RTS_DE_ALT_PORT    GPIOB
#define USART1_RTS_DE_ALT_PIN     3
#define USART1_RTS_DE_ALT_AF      7

/* ---- USART2 (USART) ---- */

#define USART2_RTS_DE_PAD     3
#define USART2_RTS_DE_PORT    GPIOA
#define USART2_RTS_DE_PIN     1
#define USART2_RTS_DE_AF      7
#define USART2_RX_PAD     6
#define USART2_RX_PORT    GPIOA
#define USART2_RX_PIN     3
#define USART2_RX_AF      7
#define USART2_TX_PAD     7
#define USART2_TX_PORT    GPIOA
#define USART2_TX_PIN     2
#define USART2_TX_AF      7
#define USART2_CTS_PAD     8
#define USART2_CTS_PORT    GPIOA
#define USART2_CTS_PIN     0
#define USART2_CTS_AF      7

/* ---- LPUART1 (LPUART) ---- */

#define LPUART1_RX_PAD     6
#define LPUART1_RX_PORT    GPIOA
#define LPUART1_RX_PIN     3
#define LPUART1_RX_AF      8
#define LPUART1_TX_PAD     7
#define LPUART1_TX_PORT    GPIOA
#define LPUART1_TX_PIN     2
#define LPUART1_TX_AF      8
#define LPUART1_CTS_PAD     9
#define LPUART1_CTS_PORT    GPIOA
#define LPUART1_CTS_PIN     6
#define LPUART1_CTS_AF      8
#define LPUART1_RTS_DE_PAD     15
#define LPUART1_RTS_DE_PORT    GPIOB
#define LPUART1_RTS_DE_PIN     1
#define LPUART1_RTS_DE_AF      8

/* ---- QSPI (QSPI) ---- */

#define QSPI_IO2_PAD     2
#define QSPI_IO2_PORT    GPIOA
#define QSPI_IO2_PIN     7
#define QSPI_IO2_AF      10
#define QSPI_CLK_PAD     6
#define QSPI_CLK_PORT    GPIOA
#define QSPI_CLK_PIN     3
#define QSPI_CLK_AF      10
#define QSPI_CS_PAD     7
#define QSPI_CS_PORT    GPIOA
#define QSPI_CS_PIN     2
#define QSPI_CS_AF      10
#define QSPI_IO3_PAD     9
#define QSPI_IO3_PORT    GPIOA
#define QSPI_IO3_PIN     6
#define QSPI_IO3_AF      10
#define QSPI_IO1_PAD     11
#define QSPI_IO1_PORT    GPIOB
#define QSPI_IO1_PIN     0
#define QSPI_IO1_AF      10
#define QSPI_IO0_PAD     15
#define QSPI_IO0_PORT    GPIOB
#define QSPI_IO0_PIN     1
#define QSPI_IO0_AF      10

#endif /* CORE_INTERFACES_H */
