/**
 * core_init.h — Generated initialization API for Core.U.2
 *
 * AUTO-GENERATED by coregen from Core-U-2-a.json + project.json
 * Project: val-rom-dfu
 *
 * DO NOT EDIT — regenerate by rebuilding the project.
 */

#ifndef CORE_INIT_H
#define CORE_INIT_H

/**
 * Initialize the core: clock tree, flash latency, and configured pads.
 * Call this at the top of main() before using any peripherals.
 */
void core_init(void);

/**
 * Initialize the clock tree only.
 * Sets up oscillator, PLL (if needed), flash wait states, bus prescalers,
 * and switches SYSCLK to the configured source.
 */
void core_clock_init(void);

/**
 * Initialize the configured pads.
 * Enables GPIO port clocks and sets modes/AF for all pads
 * assigned in project.json.
 */
void core_pads_init(void);

#endif /* CORE_INIT_H */
