/**
 * core_init.c — Generated initialization for Core.U.2
 *
 * AUTO-GENERATED by coregen from Core-U-2-a.json + config.json
 * Project: val-rom-dfu
 *
 * Clock: msi → 16MHz
 * No PLL
 *
 * DO NOT EDIT — regenerate by rebuilding the project.
 */

#include "core_init.h"
#include "core_config.h"
#include "core_pads.h"
#include "ll_rcc.h"
#include "ll_gpio.h"
#include "ll_systick.h"
#include "hal_usb_cdc.h"
#include "hal_dfu.h"


/* No pads with `exti` configured in config.json — dispatcher is a no-op.
 * Always-callable contract lets the Studio shim invoke it without
 * caring about project contents. */
void studio_dispatch_core_pad(void) { }

/* ---- Studio tick dispatcher ----
 * Polled from the DSL main loop via hal_tick(); fires the weak
 * `studio_evt_Core_Timer_tick` handler once per configured period.
 * Elapsed time is computed in unsigned ms so it's wrap-safe at the
 * ~49-day rollover. DSL overrides the weak default to run user code.
 */
__attribute__((weak)) void studio_evt_Core_Timer_tick(void) { }

/* No `timer.tick_ms` in config.json — dispatcher is a no-op. */
void studio_dispatch_core_timer(void) { }

/* ---- Studio USB-receive dispatcher ----
 * Drains the USB CDC RX ring once per main-loop iteration (capped at
 * 64 bytes so burst traffic can't starve the DSL loop). Fires the
 * weak `studio_evt_Core_USB_receive(int byte)` per byte. Gated on
 * `usb.enabled`; emits a no-op when USB isn't enabled.
 */
__attribute__((weak)) void studio_evt_Core_USB_receive(int byte) { (void)byte; }

void studio_dispatch_core_usb(void)
{
    int drained = 0;
    while (drained++ < 64 && hal_usb_cdc_available() > 0) {
        studio_evt_Core_USB_receive((int)hal_usb_cdc_getc());
    }
}

void core_clock_init(void)
{
    /* ---- No PLL — run directly from msi at 16MHz ---- */
    /* Configure MSI to 16MHz */
    ll_rcc_msi_set_range(LL_RCC_MSI_RANGE_16MHZ);
    while (!ll_rcc_msi_ready())
        ;
    ll_flash_set_latency(ll_flash_latency_for_mhz(16));
    ll_rcc_set_sysclk(LL_RCC_SYSCLK_MSI);
    ll_rcc_wait_sysclk(LL_RCC_SYSCLK_MSI);

    /* ---- Bus prescalers ---- */
    ll_rcc_set_ahb_div(1);
    ll_rcc_set_apb1_div(1);
    ll_rcc_set_apb2_div(1);

    /* ---- SysTick (1ms tick for ll_delay_ms) ---- */
    ll_systick_init(SYSCLK_HZ);

    /* ---- USB 48MHz clock (HSI48, crystal-less via CRS) ---- */
    ll_rcc_hsi48_enable();
    while (!ll_rcc_hsi48_ready())
        ;
#if defined(STM32H523xx)
    ll_rcc_set_usb_clk_source(LL_RCC_USB_HSI48);
    ll_rcc_apb2_clk_enable(LL_APB2_USB);
#else
    ll_rcc_set_usb_clk_source(LL_RCC_USB48_HSI48);
    ll_rcc_apb1_clk_enable(LL_APB1_USB);
#endif
}

void core_pads_init(void)
{
    /* No pads configured in config.json */
}

void core_init(void)
{
#ifdef ROM_DFU
    /* ROM DFU: check for magic before ANY peripheral/clock init.
     * If found, jump to the factory ROM bootloader (DfuSe, 0483:DF11).
     * The MCU is in near-reset state here — only .data/.bss init has run. */
    if (DFU_MAGIC_ADDR == DFU_MAGIC) {
        DFU_MAGIC_ADDR = 0;
        hal_dfu_jump_to_rom();  /* does not return */
    }
#endif
#ifdef APP_OFFSET
    /* Relocate vector table for bootloader builds (app not at 0x08000000) */
    REG32(0xE000ED08UL) = APP_OFFSET;
#endif

    core_clock_init();
    core_pads_init();

    /* ---- USB CDC (always-on for DFU recovery) ----
     * Ensures the 1200-baud touch mechanism works even when main.c
     * doesn't call core_usb_init() — prevents DFU lockout. */
    hal_usb_cdc_init();
}
