/**
 * core_pads.h — Pad-to-GPIO mapping for Core.U.2
 *
 * AUTO-GENERATED by coregen from Core-U-2-a.json
 * JSON version 0.49, rev a
 *
 * DO NOT EDIT — regenerate with:
 *   python3 tools/coregen/coregen.py tiles/Core-U-2-a.json
 */

#ifndef CORE_PADS_H
#define CORE_PADS_H

#include <stdint.h>

/* ---- Core identity ---- */

#define TILE_FAMILY        "Core"
#define TILE_NAME          "U.2"
#define TILE_FULL_NAME     "Core.U.2"
#define TILE_REV           "a"
#define TILE_HEADLINE      "expanded-I/0 USB-prog. Cortex-M4"
#define TILE_PAD_COUNT     22

/* ---- MCU identity ---- */

#define TILE_MCU_PART      "STM32L422TB"
#define TILE_MCU_DEFINE    STM32L422xx
#define TILE_MCU_FAMILY    "stm32l4xx"
#define TILE_MCU_CORE      "cortex-m4"

/* ---- Pad-to-GPIO mapping ---- */
/*
 * Each pad with a GPIO function gets:
 *   PAD_<n>_PORT  — GPIO port base (e.g., GPIOA)
 *   PAD_<n>_PIN   — Pin number within the port
 *   PAD_<n>_GPIO  — Combined P<port><pin> label for comments
 */

/* Pad 1: power (no GPIO) */
/* Pad 2: PA7 */
#define PAD_2_PORT       GPIOA
#define PAD_2_PIN        7
/* Pad 3: PA1 */
#define PAD_3_PORT       GPIOA
#define PAD_3_PIN        1
/* Pad 4: PB6 */
#define PAD_4_PORT       GPIOB
#define PAD_4_PIN        6
/* Pad 5: PB7 */
#define PAD_5_PORT       GPIOB
#define PAD_5_PIN        7
/* Pad 6: PA3 */
#define PAD_6_PORT       GPIOA
#define PAD_6_PIN        3
/* Pad 7: PA2 */
#define PAD_7_PORT       GPIOA
#define PAD_7_PIN        2
/* Pad 8: PA0 */
#define PAD_8_PORT       GPIOA
#define PAD_8_PIN        0
/* Pad 9: PA6 */
#define PAD_9_PORT       GPIOA
#define PAD_9_PIN        6
/* Pad 10: PA5 */
#define PAD_10_PORT       GPIOA
#define PAD_10_PIN        5
/* Pad 11: PB0 */
#define PAD_11_PORT       GPIOB
#define PAD_11_PIN        0
/* Pad 12: PB3 */
#define PAD_12_PORT       GPIOB
#define PAD_12_PIN        3
/* Pad 13: PA14 */
#define PAD_13_PORT       GPIOA
#define PAD_13_PIN        14
/* Pad 14: PA13 */
#define PAD_14_PORT       GPIOA
#define PAD_14_PIN        13
/* Pad 15: PB1 */
#define PAD_15_PORT       GPIOB
#define PAD_15_PIN        1
/* Pad 16: PA12 */
#define PAD_16_PORT       GPIOA
#define PAD_16_PIN        12
/* Pad 17: PA11 */
#define PAD_17_PORT       GPIOA
#define PAD_17_PIN        11
/* Pad 18: PB4 */
#define PAD_18_PORT       GPIOB
#define PAD_18_PIN        4
/* Pad 19: PA4 */
#define PAD_19_PORT       GPIOA
#define PAD_19_PIN        4
/* Pad 20: power (no GPIO) */
/* Pad 21: PH3 */
#define PAD_21_PORT       GPIOH
#define PAD_21_PIN        3
/* Pad 22: system/no GPIO */

/* ---- System pads ---- */

#define PAD_SWCLK          13
#define PAD_SWDIO          14
#define PAD_BOOT0          21
#define PAD_NRST           22
#define PAD_VCC            20
#define PAD_GND            1

/* ---- Pin bitmasks (for BSRR, ODR, IDR) ---- */

#define PAD_2_MASK       (1UL << 7)
#define PAD_3_MASK       (1UL << 1)
#define PAD_4_MASK       (1UL << 6)
#define PAD_5_MASK       (1UL << 7)
#define PAD_6_MASK       (1UL << 3)
#define PAD_7_MASK       (1UL << 2)
#define PAD_8_MASK       (1UL << 0)
#define PAD_9_MASK       (1UL << 6)
#define PAD_10_MASK       (1UL << 5)
#define PAD_11_MASK       (1UL << 0)
#define PAD_12_MASK       (1UL << 3)
#define PAD_13_MASK       (1UL << 14)
#define PAD_14_MASK       (1UL << 13)
#define PAD_15_MASK       (1UL << 1)
#define PAD_16_MASK       (1UL << 12)
#define PAD_17_MASK       (1UL << 11)
#define PAD_18_MASK       (1UL << 4)
#define PAD_19_MASK       (1UL << 4)
#define PAD_21_MASK       (1UL << 3)

/* ---- ADC channel mapping ---- */
/* Maps pad numbers to ADC channel numbers for pads with analog functions. */
/* Use with hal_adc_read() or the generated PAD_n_ADC_CH defines. */

#define PAD_2_ADC_CH     12
#define PAD_3_ADC_CH     6
#define PAD_6_ADC_CH     8
#define PAD_7_ADC_CH     7
#define PAD_8_ADC_CH     5
#define PAD_9_ADC_CH     11
#define PAD_10_ADC_CH     10
#define PAD_11_ADC_CH     15
#define PAD_15_ADC_CH     16

/**
 * Pad-to-ADC-channel lookup (auto-generated).
 * Returns the ADC channel for a pad, or -1 if no ADC on that pad.
 */
static inline int core_pad_adc_channel(uint8_t pad)
{
    switch (pad) {
    case 2: return 12;
    case 3: return 6;
    case 6: return 8;
    case 7: return 7;
    case 8: return 5;
    case 9: return 11;
    case 10: return 10;
    case 11: return 15;
    case 15: return 16;
    default: return -1;
    }
}


#endif /* CORE_PADS_H */
