/**
 * tiles.h — Tile driver handles and configuration for naming-test
 *
 * Initially generated by coregen. The section between coregen markers
 * is kept in sync with project.json automatically — add your own
 * tile-related defines outside the markers.
 */

#ifndef TILES_H
#define TILES_H

/* ---- coregen:begin ---- */
#include "tiles_hal.h"
#include "tiles_hal_core.h"
#include "tile_sense_i_9.h"
#include "tile_power_l_1t.h"
#include "tile_drive_p.h"

/* Tile HAL handles (one per bus used by tiles) */
tiles_hal_t core_hal_i2c3;
tiles_hal_t core_hal_i2c1;

/* Tile instance handles */
tile_t tile_sense_i_9_0;
tile_t tile_power_l_1t_0;
tile_t tile_drive_p_0;
tile_t tile_drive_p_1;
/* ---- coregen:end ---- */

#endif /* TILES_H */
