/* VERBATIM copy of the Studio-generated firmware that reads zeros, used as a
 * controlled repro. Only change: none. If this streams zeros on the bench, the
 * generated SEQUENCE is at fault; if it streams real distances, the sequence is
 * innocent and the difference lives in Studio's config.json (pads/clock/bus). */
#include "core.h"
#include "core_usb.h"
#include "core_watchdog.h"
#include "tile_sense_tof.h"

static tile_t sense_tof;

/* Generated by @bergsonne/behavior-lang — do not edit. */

/* Program state — shared between studio_main and event handlers. */
static int distance_mm = 0;

void studio_main(void) {
  core_led_heartbeat(1000, 1);
  tile_sense_tof_start(&sense_tof);
  for (;;) {
    core_watchdog_feed();
    distance_mm = tile_sense_tof_get_distance_mm(&sense_tof);
    core_usb_print_int(distance_mm);
    core_delay_ms(100);
  }
}

int main(void)
{
    core_init();
    core_usb_init();
    core_led_init();
    tile_sense_tof_init(core_tiles_pal(&core_i2c1), 0, &sense_tof, NULL);
    core_watchdog_start(5000);

    /* Hand off to the generated behavior. */
    studio_main();
    return 0;
}
