/* ---------------------------------------------------------------------
 * Generated by tools/gen_studio_natives.py - DO NOT EDIT BY HAND.
 * Regenerate when manifests/sdk-docs/ JSON files change.
 * ------------------------------------------------------------------ */


#ifndef TESSERA_NATIVES_H
#define TESSERA_NATIVES_H

#include <stddef.h>

#include "wasm_export.h"

#ifdef __cplusplus
extern "C" {
#endif

/* 32 Studio-exposed host symbols (static table). */
extern NativeSymbol g_studio_natives[];
extern const size_t g_studio_natives_count;

#ifdef __cplusplus
}
#endif

#endif /* TESSERA_NATIVES_H */
