/* ---------------------------------------------------------------------
 * Generated by tools/gen_tessera_natives.py - DO NOT EDIT BY HAND.
 * Regenerate when manifests/sdk-docs/ JSON files change.
 * ------------------------------------------------------------------ */


#include <stddef.h>
#include <stdint.h>

#include "wasm_export.h"

/* The LL layer's *_BASE macros (RCC_BASE, AHB1_BASE, …) are
 * defined via per-MCU branches in ll_common.h + ll_rcc.h and
 * referenced transitively by ll_pwr.h and friends. Projects
 * normally reach them via their auto-generated `core.h`, but
 * this TU is project-independent so we pull them in directly. */
#include "ll_common.h"
#include "ll_rcc.h"

/* SDK headers providing the host symbols we wrap. */
#include "core_backup.h"
#include "core_led.h"
#include "core_nvm.h"
#include "core_rng.h"
#include "core_rtc.h"
#include "core_timing.h"
#include "core_usb.h"
#include "core_watchdog.h"

/* Skipped at generation time:
 *   - core_adc_read_pad: category 'adc' reaches into coregen-generated state; needs per-project generation
 *   - core_adc_read_mv_pad: category 'adc' reaches into coregen-generated state; needs per-project generation
 *   - core_adc_temp_decidegc: category 'adc' reaches into coregen-generated state; needs per-project generation
 *   - core_adc_vdd_mv: category 'adc' reaches into coregen-generated state; needs per-project generation
 *   - core_dac_init: category 'dac' reaches into coregen-generated state; needs per-project generation
 *   - core_dac_write: category 'dac' reaches into coregen-generated state; needs per-project generation
 *   - core_dac_write_mv: category 'dac' reaches into coregen-generated state; needs per-project generation
 *   - core_dac_read: category 'dac' reaches into coregen-generated state; needs per-project generation
 *   - core_pad_write: category 'pad' reaches into coregen-generated state; needs per-project generation
 *   - core_pad_read: category 'pad' reaches into coregen-generated state; needs per-project generation
 *   - core_pad_toggle: category 'pad' reaches into coregen-generated state; needs per-project generation
 *   - core_pwm_duty: category 'pwm' reaches into coregen-generated state; needs per-project generation
 */

/* ---- Adapters ---------------------------------------------------------- */

/* core_backup_read  (i)i  (category: backup) */
static uint32_t core_backup_read_native(wasm_exec_env_t env, uint8_t index)
{
    (void)env;
    return core_backup_read(index);
}

/* core_backup_write  (ii)  (category: backup) */
static void core_backup_write_native(wasm_exec_env_t env, uint8_t index, uint32_t value)
{
    (void)env;
    core_backup_write(index, value);
}

/* core_led_on  ()  (category: led) */
static void core_led_on_native(wasm_exec_env_t env)
{
    (void)env;
    core_led_on();
}

/* core_led_off  ()  (category: led) */
static void core_led_off_native(wasm_exec_env_t env)
{
    (void)env;
    core_led_off();
}

/* core_led_toggle  ()  (category: led) */
static void core_led_toggle_native(wasm_exec_env_t env)
{
    (void)env;
    core_led_toggle();
}

/* core_led_blink  (iii)  (category: led) */
static void core_led_blink_native(wasm_exec_env_t env, int n, int on_ms, int off_ms)
{
    (void)env;
    core_led_blink(n, on_ms, off_ms);
}

/* core_led_heartbeat  (i)  (category: led) */
static void core_led_heartbeat_native(wasm_exec_env_t env, int period_ms)
{
    (void)env;
    core_led_heartbeat(period_ms);
}

/* core_nvm_size  ()i  (category: nvm) */
static uint32_t core_nvm_size_native(wasm_exec_env_t env)
{
    (void)env;
    return core_nvm_size();
}

/* core_rng_read  ()i  (category: rng) */
static uint32_t core_rng_read_native(wasm_exec_env_t env)
{
    (void)env;
    return core_rng_read();
}

/* core_rtc_init  ()  (category: rtc) */
static void core_rtc_init_native(wasm_exec_env_t env)
{
    (void)env;
    core_rtc_init();
}

/* core_rtc_set_time  (iii)  (category: rtc) */
static void core_rtc_set_time_native(wasm_exec_env_t env, uint8_t h, uint8_t m, uint8_t s)
{
    (void)env;
    core_rtc_set_time(h, m, s);
}

/* core_rtc_set_date  (iiii)  (category: rtc) */
static void core_rtc_set_date_native(wasm_exec_env_t env, uint8_t y, uint8_t mo, uint8_t d, uint8_t wd)
{
    (void)env;
    core_rtc_set_date(y, mo, d, wd);
}

/* core_rtc_wakeup  (i)  (category: rtc) */
static void core_rtc_wakeup_native(wasm_exec_env_t env, uint32_t seconds)
{
    (void)env;
    core_rtc_wakeup(seconds);
}

/* core_rtc_wakeup_stop  ()  (category: rtc) */
static void core_rtc_wakeup_stop_native(wasm_exec_env_t env)
{
    (void)env;
    core_rtc_wakeup_stop();
}

/* core_rtc_set_alarm  (iii)  (category: rtc) */
static void core_rtc_set_alarm_native(wasm_exec_env_t env, uint8_t hours, uint8_t minutes, uint8_t seconds)
{
    (void)env;
    core_rtc_set_alarm(hours, minutes, seconds);
}

/* core_rtc_clear_alarm  ()  (category: rtc) */
static void core_rtc_clear_alarm_native(wasm_exec_env_t env)
{
    (void)env;
    core_rtc_clear_alarm();
}

/* core_rtc_alarm_fired  ()i  (category: rtc) */
static int core_rtc_alarm_fired_native(wasm_exec_env_t env)
{
    (void)env;
    return core_rtc_alarm_fired();
}

/* core_delay_ms  (i)  (category: timing) */
static void core_delay_ms_native(wasm_exec_env_t env, uint32_t ms)
{
    (void)env;
    core_delay_ms(ms);
}

/* core_delay_us  (i)  (category: timing) */
static void core_delay_us_native(wasm_exec_env_t env, uint32_t us)
{
    (void)env;
    core_delay_us(us);
}

/* core_millis  ()i  (category: timing) */
static uint32_t core_millis_native(wasm_exec_env_t env)
{
    (void)env;
    return core_millis();
}

/* core_timeout  (ii)i  (category: timing) */
static int core_timeout_native(wasm_exec_env_t env, uint32_t start, uint32_t ms)
{
    (void)env;
    return core_timeout(start, ms);
}

/* core_usb_print  ($)  (category: usb) */
static void core_usb_print_native(wasm_exec_env_t env, const char * text)
{
    (void)env;
    core_usb_print(text);
}

/* core_usb_print_int  (i)  (category: usb) */
static void core_usb_print_int_native(wasm_exec_env_t env, int value)
{
    (void)env;
    core_usb_print_int(value);
}

/* core_usb_print_float  (F)  (category: usb) */
static void core_usb_print_float_native(wasm_exec_env_t env, double value)
{
    (void)env;
    core_usb_print_float(value);
}

/* core_usb_print_bool  (i)  (category: usb) */
static void core_usb_print_bool_native(wasm_exec_env_t env, int value)
{
    (void)env;
    core_usb_print_bool(value);
}

/* core_watchdog_start  (i)  (category: watchdog) */
static void core_watchdog_start_native(wasm_exec_env_t env, uint32_t timeout_ms)
{
    (void)env;
    core_watchdog_start(timeout_ms);
}

/* core_watchdog_feed  ()  (category: watchdog) */
static void core_watchdog_feed_native(wasm_exec_env_t env)
{
    (void)env;
    core_watchdog_feed();
}

/* ---- NativeSymbol table ----------------------------------------------- */

/* NOT const: WAMR's `wasm_runtime_register_natives` calls
 * `qsort` on the table in place (see wasm_native.c's
 * register_natives). If the array sits in .rodata the
 * qsort writes silently no-op on Cortex-M and WAMR's
 * bsearch lookup then fails with "failed to call unlinked
 * import function" — even though every symbol is present.
 * Leaving it writable puts the table in .data (RAM-backed)
 * where the sort runs correctly at startup. */
NativeSymbol g_tessera_natives[] = {
    { "core_backup_read", (void *)core_backup_read_native, "(i)i", NULL },
    { "core_backup_write", (void *)core_backup_write_native, "(ii)", NULL },
    { "core_led_on", (void *)core_led_on_native, "()", NULL },
    { "core_led_off", (void *)core_led_off_native, "()", NULL },
    { "core_led_toggle", (void *)core_led_toggle_native, "()", NULL },
    { "core_led_blink", (void *)core_led_blink_native, "(iii)", NULL },
    { "core_led_heartbeat", (void *)core_led_heartbeat_native, "(i)", NULL },
    { "core_nvm_size", (void *)core_nvm_size_native, "()i", NULL },
    { "core_rng_read", (void *)core_rng_read_native, "()i", NULL },
    { "core_rtc_init", (void *)core_rtc_init_native, "()", NULL },
    { "core_rtc_set_time", (void *)core_rtc_set_time_native, "(iii)", NULL },
    { "core_rtc_set_date", (void *)core_rtc_set_date_native, "(iiii)", NULL },
    { "core_rtc_wakeup", (void *)core_rtc_wakeup_native, "(i)", NULL },
    { "core_rtc_wakeup_stop", (void *)core_rtc_wakeup_stop_native, "()", NULL },
    { "core_rtc_set_alarm", (void *)core_rtc_set_alarm_native, "(iii)", NULL },
    { "core_rtc_clear_alarm", (void *)core_rtc_clear_alarm_native, "()", NULL },
    { "core_rtc_alarm_fired", (void *)core_rtc_alarm_fired_native, "()i", NULL },
    { "core_delay_ms", (void *)core_delay_ms_native, "(i)", NULL },
    { "core_delay_us", (void *)core_delay_us_native, "(i)", NULL },
    { "core_millis", (void *)core_millis_native, "()i", NULL },
    { "core_timeout", (void *)core_timeout_native, "(ii)i", NULL },
    { "core_usb_print", (void *)core_usb_print_native, "($)", NULL },
    { "core_usb_print_int", (void *)core_usb_print_int_native, "(i)", NULL },
    { "core_usb_print_float", (void *)core_usb_print_float_native, "(F)", NULL },
    { "core_usb_print_bool", (void *)core_usb_print_bool_native, "(i)", NULL },
    { "core_watchdog_start", (void *)core_watchdog_start_native, "(i)", NULL },
    { "core_watchdog_feed", (void *)core_watchdog_feed_native, "()", NULL },
};

const size_t g_tessera_natives_count =
    sizeof(g_tessera_natives) / sizeof(g_tessera_natives[0]);
