/**
 * tiles.h — Tile driver handles and configuration for sdk-demo
 *
 * Initially generated by coregen. The section between coregen markers
 * is kept in sync with project.json automatically — add your own
 * tile-related defines outside the markers.
 */

#ifndef TILES_H
#define TILES_H

/* ---- coregen:begin ---- */
#include "tiles_hal.h"
#include "tiles_hal_core.h"
#include "tile_sense_i_9.h"

/* Tile HAL handles (one per bus used by tiles) */
tiles_hal_t core_hal_i2c3;

/* Tile instance handles */
tile_t tile_sense_i_9_0;
/* ---- coregen:end ---- */

#endif /* TILES_H */
