/**
 * tile_handles.h — Tile driver includes and instance handles for sdk-demo
 *
 * Initially generated by coregen. The section between coregen markers
 * is kept in sync with project.json automatically — add your own
 * tile-related defines outside the markers.
 *
 * Named tile_handles.h (not tiles.h) so it doesn't shadow kiln/tiles.h
 * in the compiler include path.
 */

#ifndef TILE_HANDLES_H
#define TILE_HANDLES_H

/* ---- coregen:begin ---- */
#include "tiles.h"
#include "tiles_hal.h"
#include "tiles_hal_core.h"
#include "tile_sense_i_9.h"

/* Tile HAL handles (one per bus used by tiles) */
tiles_hal_t core_hal_i2c3;

/* Tile instance handles */
tile_t tile_sense_i_9_i2c3_0;
/* ---- coregen:end ---- */

#endif /* TILE_HANDLES_H */
