#!/usr/bin/env python3
"""
gen_active_tiles.py — generate manifests/active-tiles.json from the product DB.

active-tiles.json is Studio's *visibility gate*: the list of driver stems Studio
surfaces as "driver-ready". It is the intersection of two things:

  • tiles flagged visible=1 in the canonical product DB (`tiles.visible`) — the
    explicit, product-side "show this in Studio" decision, set in the portal; and
  • tiles that actually have a driver manifest here (manifests/tile_*.json).

The intersection is the safety net: a tile flagged visible with no driver yet is
reported and left out, so Studio never claims driverReady for a missing manifest.

Like sync_definitions.py this reads the DB (there is no git-tree source for the
`visible` flag), so it runs in the sync-definitions workflow (which has
TILES_DB_PASSWORD) — NOT the studio-manifest --check gate, which has no DB.

Connection: same env as sync_definitions.py (TILES_DB_*); the password has no
default and must be supplied.

Usage:
    TILES_DB_PASSWORD=… python3 tools/gen_active_tiles.py            # dry-run
    TILES_DB_PASSWORD=… python3 tools/gen_active_tiles.py --apply
    TILES_DB_PASSWORD=… python3 tools/gen_active_tiles.py --check    # needs DB
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import mysql.connector

ROOT = Path(__file__).resolve().parent.parent
MANIFESTS = ROOT / "manifests"
ACTIVE_TILES = MANIFESTS / "active-tiles.json"

DB = dict(
    host=os.environ.get("TILES_DB_HOST", "library.c1cuew2e6bhd.eu-north-1.rds.amazonaws.com"),
    port=int(os.environ.get("TILES_DB_PORT", "3306")),
    user=os.environ.get("TILES_DB_USER", "web"),
    password=os.environ.get("TILES_DB_PASSWORD", ""),
    database=os.environ.get("TILES_DB_NAME", "library"),
)

COMMENT = (
    "GENERATED by tools/gen_active_tiles.py from the product DB `tiles.visible` "
    "column intersected with the driver manifests here. Studio's visibility gate "
    "(consumed by the web studio's tileCatalog.ts). Do not hand-edit — flip a "
    "tile's visibility in the portal and re-run the sync."
)


def stem(family: str, name: str) -> str:
    """Sense + BP -> tile_sense_bp ; Sense + I.6P6 -> tile_sense_i_6p6."""
    return "tile_" + f"{family}.{name}".lower().replace(".", "_")


def driver_registry() -> set[str]:
    """Driver stems that have a Studio palette manifest committed here."""
    return {p.stem for p in MANIFESTS.glob("tile_*.json")}


def build() -> tuple[str, list[str]]:
    if not DB["password"]:
        print("ERROR: set TILES_DB_PASSWORD (no credentials are stored in the repo).",
              file=sys.stderr)
        sys.exit(2)

    conn = mysql.connector.connect(connection_timeout=20, **DB)
    cur = conn.cursor()
    cur.execute(
        """
        SELECT f.name AS family, t.name, t.visible
        FROM tiles t
        JOIN tile_families f ON t.tile_family_id = f.id
        """
    )
    rows = cur.fetchall()
    cur.close()
    conn.close()

    registry = driver_registry()
    visible: set[str] = set()
    no_driver: set[str] = set()
    for family, name, is_visible in rows:
        if not is_visible:
            continue
        s = stem(family, name)
        if s in registry:
            visible.add(s)
        elif family != "Core":
            # Cores are boards, not Studio peripheral tiles (they have no
            # tile_*.json) — being visible elsewhere is expected, so don't warn.
            no_driver.add(s)

    for s in sorted(no_driver):
        print(f"  WARNING: {s} is visible=1 in the DB but has no driver manifest — skipped",
              file=sys.stderr)

    tiles = sorted(visible)
    text = json.dumps({"_comment": COMMENT, "tiles": tiles}, indent=2, ensure_ascii=False) + "\n"
    return text, tiles


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate manifests/active-tiles.json from the DB `visible` column."
    )
    ap.add_argument("--apply", action="store_true", help="write changes (default: dry-run)")
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed file is stale (requires DB)")
    args = ap.parse_args()

    text, tiles = build()
    have = ACTIVE_TILES.read_text(encoding="utf-8") if ACTIVE_TILES.exists() else ""

    if args.check:
        if text != have:
            print("active-tiles.json is stale — run: python3 tools/gen_active_tiles.py --apply",
                  file=sys.stderr)
            return 1
        print(f"active-tiles.json in sync ({len(tiles)} visible tiles)")
        return 0

    if text == have:
        print(f"active-tiles.json already current ({len(tiles)} visible tiles)")
        return 0
    print(f"{'WROTE' if args.apply else 'DIFF (dry-run)'}: active-tiles.json ({len(tiles)} visible tiles)")
    if args.apply:
        MANIFESTS.mkdir(exist_ok=True)
        ACTIVE_TILES.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
